// src/svelte/element.svelte
<div class={getQuestionClass(element, css)}>
    {#if element.hasTitleOnLeftTop}
        <div class={element.hasTitleOnLeft ? 'title-left' : ''}>
            {#if element.hasTitle}
                <h5 class={element.cssClasses.title}>
                    <SurveyString locString={element.locTitle} />
                </h5>
            {/if}
            {#if element.hasDescription}
                <div class={element.cssClasses.description}>
                    <SurveyString locString={element.locDescription} />
                </div>
            {/if}
        </div>
    {/if}

    <div class={element.hasTitleOnLeft ? 'content-left' : ''}>
        {#if hasErrorsOnTop}           
            <SurveyErrors question={element} />
        {/if}

        <svelte:component this={dynamicComponent} question={element} css={css}/>
        
        {#if element.hasComment}
            <div>
                <div>{element.commentText}</div>
                <OtherChoice commentClass={css.comment} question={element} />
            </div>
        {/if}

        {#if hasErrorsOnBottom}
            <SurveyErrors question={element} />
        {/if}

        {#if element.hasTitleOnBottom}
            <h5 class={element.cssClasses.title}>
                <SurveyString locString={element.locTitle} />
            </h5>
        {/if}
        {#if element.hasDescription}
            <div class:sjs-hide="!element.hasTitleOnBottom" class={element.cssClasses.description}>
                <SurveyString locString={element.locDescription} />
            </div>
        {/if}
    </div>
</div>

<script>
  import SurveyString from "./string.svelte";
  import SurveyErrors from "./errors.svelte";
  import OtherChoice from "./otherChoice.svelte";
  import { listenArrayChanged } from "./utils";

  import radiogroup from "./radiogroup.svelte";
  import checkbox from "./checkbox.svelte";
  import comment from "./comment.svelte";
  import matrix from "./matrix.svelte";
  import matrixdropdown from "./matrixdropdown.svelte";

  export default {
    data() {
      return {
        survey: null,
        css: null,
        element: null
      };
    },
    components: {
      SurveyString,
      SurveyErrors,
      OtherChoice
    },
    onupdate() {
      const element = this.get().element;
      listenArrayChanged(element, () => {
        this.set({ element, ...element });
      });
    },
    helpers: {
      getQuestionClass(element, css) {
        if (!!element.errors && element.errors.length > 0) {
          return css.question.hasError;
        }
        return "";
      }
    },
    computed: {
      hasErrorsOnTop: ({ survey, element }) => {
        return !element.isPanel && survey.questionErrorLocation === "top";
      },
      hasErrorsOnBottom: ({ survey, element }) => {
        return !element.isPanel && survey.questionErrorLocation === "bottom";
      },
      dynamicComponent: ({ element }) => {
        if (element.customWidget) return "customwidget";
        const components = {
          radiogroup,
          checkbox,
          comment,
          matrix,
          matrixdropdown
        };
        return components[element.getTemplate()];
      }
    }
  };
</script>

// src/vue/element.vue
<template>
    <div :class="getQuestionClass(element)">
        <div v-if="element.hasTitleOnLeftTop" :class="element.hasTitleOnLeft ? 'title-left' : ''">
            <h5 v-if="element.hasTitle" :class="element.cssClasses.title"><survey-string :locString="element.locTitle"/></h5>
            <div :class="element.cssClasses.description"><survey-string :locString="element.locDescription"/></div>
        </div>
        <div :class="element.hasTitleOnLeft ? 'content-left' : ''">
            <survey-errors v-if="hasErrorsOnTop" :question="element"/>
            <component :is="getWidgetComponentName(element)" :question="element" :css="css"/>
            <div v-if="element.hasComment">
                <div>{{element.commentText}}</div>
                <survey-other-choice :commentClass="css.comment" :question="element"/>
            </div>
            <survey-errors v-if="hasErrorsOnBottom" :question="element"/>
            <h5 v-if="element.hasTitleOnBottom" :class="element.cssClasses.title"><survey-string :locString="element.locTitle"/></h5>
            <div v-show="element.hasTitleOnBottom"><survey-string :locString="element.locDescription"/></div>
        </div>
    </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { SurveyModel } from "../survey";
import { IElement, IQuestion } from "../base";
import { Question } from "../question";

@Component
export class SurveyElementVue extends Vue {
  @Prop() css: any;
  @Prop() survey: SurveyModel;
  @Prop() element: IElement;

  getWidgetComponentName(element: Question) {
    if (element.customWidget) {
      return "survey-customwidget";
    }
    return "survey-" + element.getTemplate();
  }
  getQuestionClass(element: Question) {
    if (!!element.errors && element.errors.length > 0) {
      return this.css.question.hasError;
    }
    return "";
  }
  get hasErrorsOnTop() {
    return !this.element.isPanel && this.survey.questionErrorLocation === "top";
  }
  get hasErrorsOnBottom() {
    return (
      !this.element.isPanel && this.survey.questionErrorLocation === "bottom"
    );
  }
  mounted() {
    if (this.survey && !this.element.isPanel) {
      this.survey.afterRenderQuestion(<IQuestion>this.element, this.$el);
    }
  }
}
Vue.component("survey-element", SurveyElementVue);
export default SurveyElementVue;
</script>
